spark.master                     yarn
spark.submit.deployMode          client
spark.driver.memory              2g
spark.driver.cores               2
# spark.executor.memory            4g
# spark.executor.cores             4
# spark.executor.instances         8
spark.yarn.executor.memoryOverhead 512
spark.default.parallelism        8
spark.sql.shuffle.partitions     48
spark.eventLog.enabled           true
spark.eventLog.dir               hdfs://__MASTER_HOST__:9000/spark-logs
spark.history.fs.logDirectory    hdfs://__MASTER_HOST__:9000/spark-logs     
spark.ui.port                    4040
spark.dynamicAllocation.enabled  true
spark.shuffle.service.enabled     true
spark.jars.packages              graphframes:graphframes:0.8.3-spark3.5-s_2.12
